version: "3"

services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8081"
        environment:
            - WWWUSER=${WWWUSER}
            - WWWGROUP=${WWWGROUP}
        volumes:
            - .:/var/www/html
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - mailpit
        command: >
            bash -c "
            composer install &&
            chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
            chown -R www-data:www-data /var/www/html &&
            php artisan optimize:clear &&
            exec apache2-foreground"

    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - sail-mysql:/var/lib/mysql
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        volumes:
            - sail-redis:/data
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
